sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: hzxfhccp414
  # todo 阿里云敏感信息
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
    # todo 小程序敏感信息
  wechat:
    appid:
    secret:
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl: https://27acc8bd.r21.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://27acc8bd.r21.cpolar.top/notify/refundSuccess